"""Explicit live-parent migrator for inventory-truth rehearsal.

Creates only inventory_item, purchase_record, and sale. Does not use
metadata.create_all. Types follow the live SQLAlchemy models compiled for
PostgreSQL. Shop-scoped unique (shop_id, id) keys match the frozen truth
composite FK names. Sale.show_session_id stays a nullable string with no FK.

API receives SELECT only. Worker and readonly receive no table access.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine

from app.database import engine as default_engine
from app.inventory_truth.migrator import TRUTH_TABLE_NAMES, apply as apply_truth

LIVE_TABLES = ("inventory_item", "purchase_record", "sale")
REHEARSAL_TABLES = LIVE_TABLES + TRUTH_TABLE_NAMES
MIGRATOR_ROLE = "stashtab_migrator"
API_ROLE = "stashtab_api"
WORKER_ROLE = "stashtab_worker"
READONLY_ROLE = "stashtab_readonly"
_RUNTIME_ROLES = (API_ROLE, WORKER_ROLE, READONLY_ROLE)
_TABLE_PRIVS = (
    "SELECT",
    "INSERT",
    "UPDATE",
    "DELETE",
    "TRUNCATE",
    "REFERENCES",
    "TRIGGER",
)
_API_PRIVS = frozenset({"SELECT"})
_ROLE_RE = re.compile(r"^[a-z][a-z0-9_]*$")
_COLUMN_RE = re.compile(r"^[a-z][a-z0-9_]*$")
# AMENDMENT-1.3.0 §4/§7: F2 controlled-receive envelope. Opt-in only —
# never applied by apply()/apply_rehearsal(); the default policy stays
# SELECT-only everywhere.
F2_CLIENT_KEY_COLUMN = "client_idempotency_key"
F2_CLIENT_KEY_INDEX = "uq_purchase_record_shop_client_key"
_F2_GRANT_TABLES = ("inventory_item", "purchase_record", "acquisition_lot", "inventory_event")
_F2_TABLE_PRIVS = {
    "inventory_item": frozenset({"SELECT", "INSERT"}),  # UPDATE is column-scoped
    "purchase_record": frozenset({"SELECT", "INSERT"}),
    "acquisition_lot": frozenset({"SELECT", "INSERT"}),
    "inventory_event": frozenset({"SELECT", "INSERT"}),
}
_F2_UPDATE_COLUMNS = ("stock", "cost")
_F2_SEQUENCES = (
    "inventory_item_id_seq",
    "purchase_record_id_seq",
    "acquisition_lot_id_seq",
    "inventory_event_id_seq",
)
_TRUTH_DROP_ORDER = (
    "inventory_adjustment",
    "return_record",
    "refund_record",
    "inventory_exception",
    "inventory_channel_observation",
    "inventory_event",
    "acquisition_lot",
    "inventory_truth_cutover",
)
_LIVE_DROP_ORDER = ("sale", "purchase_record", "inventory_item")

_CREATE_INVENTORY_ITEM = """
CREATE TABLE IF NOT EXISTS inventory_item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id VARCHAR(36) NOT NULL,
    sku VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    set_name VARCHAR(100),
    sequence_number VARCHAR(50),
    cost DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    old_price DOUBLE PRECISION,
    card_type VARCHAR(50),
    variant VARCHAR(50),
    condition VARCHAR(50),
    stock INTEGER NOT NULL,
    last_sync TIMESTAMP WITH TIME ZONE,
    date_added TIMESTAMP WITH TIME ZONE NOT NULL,
    needs_update BOOLEAN NOT NULL,
    needs_review BOOLEAN NOT NULL,
    image_url VARCHAR(512),
    image_locked BOOLEAN NOT NULL,
    sync_status VARCHAR(50) NOT NULL,
    custom_image_url VARCHAR(512),
    shop_listing_price DOUBLE PRECISION,
    sticker_price DOUBLE PRECISION,
    paused_stock INTEGER NOT NULL,
    game VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_inventory_shop_sku UNIQUE (shop_id, sku)
)
"""

_CREATE_PURCHASE_RECORD = """
CREATE TABLE IF NOT EXISTS purchase_record (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id VARCHAR(36) NOT NULL,
    sku VARCHAR(50) NOT NULL,
    quantity INTEGER NOT NULL,
    cost_per_unit DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
)
"""

_CREATE_SALE = """
CREATE TABLE IF NOT EXISTS sale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id VARCHAR(36) NOT NULL,
    item_name VARCHAR(100),
    sku VARCHAR(50),
    sold_price DOUBLE PRECISION,
    profit DOUBLE PRECISION,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    transaction_type VARCHAR(20),
    trade_in_value DOUBLE PRECISION NOT NULL,
    processing_fees DOUBLE PRECISION NOT NULL,
    trade_credit_deduction DOUBLE PRECISION NOT NULL,
    net_revenue DOUBLE PRECISION NOT NULL,
    game VARCHAR(50) NOT NULL,
    show_session_id VARCHAR(36),
    is_reconciled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
)
"""


def _ident(role: str) -> str:
    if not _ROLE_RE.fullmatch(role):
        raise RuntimeError("invalid role name")
    return role


def _role_exists(conn, role: str) -> bool:
    return bool(
        conn.execute(
            text("SELECT 1 FROM pg_roles WHERE rolname = :r"),
            {"r": role},
        ).scalar()
    )


def _role_can_assume(conn, member: str, role: str) -> bool:
    return bool(
        conn.execute(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM pg_auth_members m
                    JOIN pg_roles r ON r.oid = m.roleid
                    JOIN pg_roles u ON u.oid = m.member
                    WHERE r.rolname = :role
                      AND u.rolname = :member
                )
                """
            ),
            {"member": member, "role": role},
        ).scalar()
    )


def _assert_runtime_cannot_assume_migrator(conn) -> None:
    migrator = _ident(MIGRATOR_ROLE)
    blocked = []
    for member in _RUNTIME_ROLES:
        if not _role_exists(conn, member):
            continue
        if _role_can_assume(conn, member, migrator):
            blocked.append(member)
    if blocked:
        raise RuntimeError(
            "prohibited membership: "
            + ",".join(blocked)
            + " can assume stashtab_migrator"
        )


def _has_table_privilege(conn, role: str, table: str, priv: str) -> bool:
    return bool(
        conn.execute(
            text("SELECT has_table_privilege(:role, :rel, :priv)"),
            {"role": role, "rel": f"public.{table}", "priv": priv},
        ).scalar()
    )


def _public_has_table_privilege(conn, table: str, priv: str) -> bool:
    return bool(
        conn.execute(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl, '{}'::aclitem[])) a
                    WHERE n.nspname = 'public'
                      AND c.relname = :table
                      AND a.grantee = 0
                      AND a.privilege_type = :priv
                )
                """
            ),
            {"table": table, "priv": priv},
        ).scalar()
    )


def _public_tables(conn) -> list[str]:
    rows = conn.execute(
        text(
            """
            SELECT c.relname FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND c.relkind = 'r'
            ORDER BY 1
            """
        )
    )
    return [r[0] for r in rows]


def _index_names(conn, table: str) -> set[str]:
    rows = conn.execute(
        text(
            """
            SELECT indexname FROM pg_indexes
            WHERE schemaname = 'public' AND tablename = :table
            """
        ),
        {"table": table},
    )
    return {r[0] for r in rows}


def _constraint_names(conn, table: str) -> set[str]:
    rows = conn.execute(
        text(
            """
            SELECT con.conname
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
            WHERE nsp.nspname = 'public' AND rel.relname = :table
            """
        ),
        {"table": table},
    )
    return {r[0] for r in rows}


def _ensure_index(conn, name: str, table: str, columns: str, unique: bool = False) -> bool:
    if name in _index_names(conn, table):
        return False
    unique_sql = "UNIQUE " if unique else ""
    conn.execute(text(f"CREATE {unique_sql}INDEX IF NOT EXISTS {name} ON {table} ({columns})"))
    return True


def _ensure_shop_fk(conn, table: str) -> bool:
    name = f"fk_{table}_shop_id"
    if name in _constraint_names(conn, table):
        return False
    conn.execute(
        text(
            f"ALTER TABLE {table} ADD CONSTRAINT {name} "
            "FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE RESTRICT"
        )
    )
    return True


def _normalize_privileges(conn, tables: tuple[str, ...]) -> list[str]:
    grants: list[str] = []
    conn.execute(
        text("ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC")
    )
    for role in _RUNTIME_ROLES:
        if _role_exists(conn, role):
            conn.execute(
                text(
                    "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
                    f"REVOKE ALL ON TABLES FROM {_ident(role)}"
                )
            )
    api = _ident(API_ROLE)
    for table in tables:
        conn.execute(text(f"REVOKE ALL PRIVILEGES ON TABLE {table} FROM PUBLIC"))
        for role in _RUNTIME_ROLES:
            if _role_exists(conn, role):
                conn.execute(
                    text(f"REVOKE ALL PRIVILEGES ON TABLE {table} FROM {_ident(role)}")
                )
        if _role_exists(conn, api):
            conn.execute(text(f"GRANT SELECT ON TABLE {table} TO {api}"))
            grants.append(f"{api}:{table}:select")
    return grants


def _assert_select_only(conn, tables: tuple[str, ...]) -> None:
    for table in tables:
        for priv in _TABLE_PRIVS:
            if _public_has_table_privilege(conn, table, priv):
                raise RuntimeError(f"PUBLIC has {priv} on {table}")
        if _role_exists(conn, API_ROLE):
            allowed = {
                priv for priv in _TABLE_PRIVS if _has_table_privilege(conn, API_ROLE, table, priv)
            }
            if allowed != _API_PRIVS:
                raise RuntimeError(
                    f"stashtab_api privileges on {table} are {sorted(allowed)}, "
                    f"expected {sorted(_API_PRIVS)}"
                )
        for role in (WORKER_ROLE, READONLY_ROLE):
            if not _role_exists(conn, role):
                continue
            held = {
                priv for priv in _TABLE_PRIVS if _has_table_privilege(conn, role, table, priv)
            }
            if held:
                raise RuntimeError(f"{role} has table privileges on {table}: {sorted(held)}")


def _has_sequence(conn, name: str) -> bool:
    return bool(
        conn.execute(
            text(
                """
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'public' AND c.relname = :s AND c.relkind = 'S'
                """
            ),
            {"s": name},
        ).scalar()
    )


def _has_column_privilege(conn, role: str, table: str, column: str, priv: str) -> bool:
    return bool(
        conn.execute(
            text("SELECT has_column_privilege(:role, :rel, :col, :priv)"),
            {"role": role, "rel": f"public.{table}", "col": column, "priv": priv},
        ).scalar()
    )


def _table_columns(conn, table: str) -> list[str]:
    rows = conn.execute(
        text(
            """
            SELECT column_name FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = :table
            ORDER BY ordinal_position
            """
        ),
        {"table": table},
    )
    return [r[0] for r in rows]


def _grant_f2_envelope(conn) -> list[str]:
    """AMENDMENT-1.3.0 §7 grant envelope for `stashtab_api` on exactly the
    four named objects. Runs under SET LOCAL ROLE stashtab_migrator.
    Column-scoped UPDATE (stock, cost) contains every unrelated write."""
    grants: list[str] = []
    api = _ident(API_ROLE)
    for table in _F2_GRANT_TABLES:
        conn.execute(text(f"REVOKE ALL PRIVILEGES ON TABLE {table} FROM PUBLIC"))
        for role in _RUNTIME_ROLES:
            if _role_exists(conn, role):
                conn.execute(
                    text(f"REVOKE ALL PRIVILEGES ON TABLE {table} FROM {_ident(role)}")
                )
    if not _role_exists(conn, api):
        return grants
    for table in _F2_GRANT_TABLES:
        conn.execute(text(f"GRANT SELECT ON TABLE {table} TO {api}"))
        grants.append(f"{api}:{table}:select")
        conn.execute(text(f"GRANT INSERT ON TABLE {table} TO {api}"))
        grants.append(f"{api}:{table}:insert")
    conn.execute(text(f"REVOKE UPDATE ON TABLE inventory_item FROM {api}"))
    conn.execute(
        text(
            f"GRANT UPDATE ({', '.join(_F2_UPDATE_COLUMNS)}) "
            f"ON TABLE inventory_item TO {api}"
        )
    )
    grants.append(f"{api}:inventory_item:update({','.join(_F2_UPDATE_COLUMNS)})")
    for seq in _F2_SEQUENCES:
        if _has_sequence(conn, seq):
            conn.execute(text(f"GRANT USAGE ON SEQUENCE {seq} TO {api}"))
            grants.append(f"{api}:{seq}:usage")
    return grants


def _assert_f2_policy(conn, tables: tuple[str, ...]) -> None:
    """Per-table policy assert (DIRECTIVE-F2 §2): the §7 envelope on the
    four named objects, SELECT-only on every other staging table, no
    PUBLIC/worker/readonly access, UPDATE confined to stock/cost, and no
    migrator assumption. PostgreSQL only — SQLite has no ACLs."""
    if conn.dialect.name != "postgresql":
        return
    api = _ident(API_ROLE)
    for table in tables:
        expected = _F2_TABLE_PRIVS.get(table, _API_PRIVS)
        for priv in _TABLE_PRIVS:
            if _public_has_table_privilege(conn, table, priv):
                raise RuntimeError(f"PUBLIC has {priv} on {table}")
        if _role_exists(conn, API_ROLE):
            allowed = {
                priv for priv in _TABLE_PRIVS if _has_table_privilege(conn, API_ROLE, table, priv)
            }
            if allowed != expected:
                raise RuntimeError(
                    f"stashtab_api privileges on {table} are {sorted(allowed)}, "
                    f"expected {sorted(expected)}"
                )
        for role in (WORKER_ROLE, READONLY_ROLE):
            if not _role_exists(conn, role):
                continue
            held = {
                priv for priv in _TABLE_PRIVS if _has_table_privilege(conn, role, table, priv)
            }
            if held:
                raise RuntimeError(f"{role} has table privileges on {table}: {sorted(held)}")
    if _role_exists(conn, API_ROLE):
        for column in _table_columns(conn, "inventory_item"):
            expected_update = column in _F2_UPDATE_COLUMNS
            if _has_column_privilege(conn, API_ROLE, "inventory_item", column, "UPDATE") != expected_update:
                raise RuntimeError(
                    f"stashtab_api UPDATE containment violated on inventory_item.{column}"
                )
        for seq in _F2_SEQUENCES:
            if _has_sequence(conn, seq) and not bool(
                conn.execute(
                    text("SELECT has_sequence_privilege(:role, :seq, 'USAGE')"),
                    {"role": API_ROLE, "seq": f"public.{seq}"},
                ).scalar()
            ):
                raise RuntimeError(f"stashtab_api lacks USAGE on {seq}")
    _assert_runtime_cannot_assume_migrator(conn)


def apply_f2_receive(
    target_engine: Engine | None = None, *, fail_after: str | None = None
) -> dict[str, list[str]]:
    """AMENDMENT-1.3.0 §4: additive client idempotency key column, partial
    unique index, §7 runtime grants, and the per-table policy assert — ONE
    atomic reviewed-migrator transaction. Opt-in only; rerun is a no-op;
    injected mid-failure leaves nothing partial."""
    engine = target_engine or default_engine
    migrator = _ident(MIGRATOR_ROLE)
    applied: dict[str, list[str]] = {"columns": [], "indexes": [], "grants": []}
    with engine.begin() as conn:
        is_pg = conn.dialect.name == "postgresql"
        if is_pg:
            if not _role_exists(conn, migrator):
                raise RuntimeError("stashtab_migrator role is missing")
            _assert_runtime_cannot_assume_migrator(conn)
            conn.execute(text(f"SET LOCAL ROLE {migrator}"))
        insp = inspect(conn)
        if not insp.has_table("purchase_record"):
            raise RuntimeError("purchase_record is missing; apply the live schema first")
        columns = {col["name"] for col in insp.get_columns("purchase_record")}
        if F2_CLIENT_KEY_COLUMN not in columns:
            if_clause = " IF NOT EXISTS" if is_pg else ""
            conn.execute(
                text(
                    f"ALTER TABLE purchase_record ADD COLUMN{if_clause} "
                    f"{F2_CLIENT_KEY_COLUMN} VARCHAR(36)"
                )
            )
            applied["columns"].append(f"purchase_record.{F2_CLIENT_KEY_COLUMN}")
        if fail_after == "column":
            raise RuntimeError("injected f2 failure after column")
        index_names = _index_names(conn, "purchase_record") if is_pg else {
            ix["name"] for ix in insp.get_indexes("purchase_record")
        }
        if F2_CLIENT_KEY_INDEX not in index_names:
            conn.execute(
                text(
                    f"CREATE UNIQUE INDEX IF NOT EXISTS {F2_CLIENT_KEY_INDEX} "
                    f"ON purchase_record (shop_id, {F2_CLIENT_KEY_COLUMN}) "
                    f"WHERE {F2_CLIENT_KEY_COLUMN} IS NOT NULL"
                )
            )
            applied["indexes"].append(F2_CLIENT_KEY_INDEX)
        if fail_after == "index":
            raise RuntimeError("injected f2 failure after index")
        if is_pg:
            applied["grants"] = _grant_f2_envelope(conn)
            if fail_after == "grants":
                raise RuntimeError("injected f2 failure after grants")
            conn.execute(text("RESET ROLE"))
            _assert_f2_policy(conn, REHEARSAL_TABLES)
    return applied


def rollback_f2_receive_grants(target_engine: Engine | None = None) -> dict[str, list[str]]:
    """Evidence-preserving rollback (AMENDMENT-1.3.0 §12): revoke the §7
    envelope back to SELECT-only. Keeps the column, the partial unique
    index, and every evidence row; no DELETE, no column drop."""
    engine = target_engine or default_engine
    with engine.begin() as conn:
        if conn.dialect.name != "postgresql":
            return {"grants": []}
        migrator = _ident(MIGRATOR_ROLE)
        if not _role_exists(conn, migrator):
            raise RuntimeError("stashtab_migrator role is missing")
        conn.execute(text(f"SET LOCAL ROLE {migrator}"))
        grants = _normalize_privileges(conn, REHEARSAL_TABLES)
        if _role_exists(conn, API_ROLE):
            api = _ident(API_ROLE)
            for seq in _F2_SEQUENCES:
                if _has_sequence(conn, seq):
                    conn.execute(text(f"REVOKE ALL ON SEQUENCE {seq} FROM {api}"))
        conn.execute(text("RESET ROLE"))
        _assert_select_only(conn, REHEARSAL_TABLES)
    return {"grants": grants}


def apply(target_engine: Engine | None = None, *, fail_after: str | None = None) -> dict[str, list[str]]:
    """Create the three live parents in one transaction. Idempotent."""
    engine = target_engine or default_engine
    migrator = _ident(MIGRATOR_ROLE)
    applied: dict[str, list[str]] = {"tables": [], "indexes": [], "foreign_keys": [], "grants": []}
    with engine.begin() as conn:
        if not _role_exists(conn, migrator):
            raise RuntimeError("stashtab_migrator role is missing")
        _assert_runtime_cannot_assume_migrator(conn)
        conn.execute(text(f"SET LOCAL ROLE {migrator}"))
        before = set(_public_tables(conn))
        conn.execute(text(_CREATE_INVENTORY_ITEM))
        conn.execute(text(_CREATE_PURCHASE_RECORD))
        conn.execute(text(_CREATE_SALE))
        for table in LIVE_TABLES:
            if table not in before:
                applied["tables"].append(table)
            conn.execute(text(f"ALTER TABLE {table} OWNER TO {migrator}"))
        if fail_after == "tables":
            raise RuntimeError("injected migration failure after tables")
        for table, sku_index in (
            ("inventory_item", "ix_inventory_item_sku"),
            ("purchase_record", "ix_purchase_record_sku"),
            ("sale", "ix_sale_sku"),
        ):
            if _ensure_index(conn, f"ix_{table}_shop_id", table, "shop_id"):
                applied["indexes"].append(f"ix_{table}_shop_id")
            if _ensure_index(conn, sku_index, table, "sku"):
                applied["indexes"].append(sku_index)
            if _ensure_index(conn, f"uq_{table}_shop_id", table, "shop_id, id", unique=True):
                applied["indexes"].append(f"uq_{table}_shop_id")
        if fail_after == "uniques":
            raise RuntimeError("injected migration failure after uniques")
        for table in LIVE_TABLES:
            if _ensure_shop_fk(conn, table):
                applied["foreign_keys"].append(f"fk_{table}_shop_id")
        if fail_after == "fks":
            raise RuntimeError("injected migration failure after fks")
        applied["grants"] = _normalize_privileges(conn, LIVE_TABLES)
        conn.execute(text("RESET ROLE"))
        _assert_select_only(conn, LIVE_TABLES)
    with engine.connect() as probe:
        names = set(_public_tables(probe))
        missing = [table for table in LIVE_TABLES if table not in names]
        if missing:
            raise RuntimeError(f"live schema verification failed, missing {missing}")
        extra_live = [name for name in ("staging_item", "show_sessions", "pending_trades") if name in names]
        if extra_live:
            raise RuntimeError(f"live schema created forbidden tables: {extra_live}")
        _assert_select_only(probe, LIVE_TABLES)
    return applied


def apply_rehearsal(target_engine: Engine | None = None) -> dict[str, dict[str, list[str]]]:
    """Apply live parents, then the committed truth migrator, then SELECT grants."""
    engine = target_engine or default_engine
    live = apply(engine)
    names = set()
    with engine.connect() as conn:
        names = set(_public_tables(conn))
    missing_parents = [table for table in LIVE_TABLES if table not in names]
    if missing_parents:
        raise RuntimeError(f"truth apply blocked; live parents missing: {missing_parents}")
    previous = os.environ.get("STASHTAB_TRUTH_MIGRATOR_ROLE")
    os.environ["STASHTAB_TRUTH_MIGRATOR_ROLE"] = MIGRATOR_ROLE
    try:
        truth = apply_truth(engine)
    finally:
        if previous is None:
            os.environ.pop("STASHTAB_TRUTH_MIGRATOR_ROLE", None)
        else:
            os.environ["STASHTAB_TRUTH_MIGRATOR_ROLE"] = previous
    with engine.begin() as conn:
        conn.execute(text(f"SET LOCAL ROLE {_ident(MIGRATOR_ROLE)}"))
        grants = _normalize_privileges(conn, REHEARSAL_TABLES)
        conn.execute(text("RESET ROLE"))
        _assert_select_only(conn, REHEARSAL_TABLES)
    return {"live": live, "truth": {k: v for k, v in truth.items() if isinstance(v, list)}, "grants": grants}


def rollback(target_engine: Engine | None = None) -> dict[str, list[str]]:
    """Drop the three live parents. Refuses if truth tables still exist."""
    engine = target_engine or default_engine
    with engine.connect() as probe:
        existing = set(_public_tables(probe))
    leftover_truth = [name for name in TRUTH_TABLE_NAMES if name in existing]
    if leftover_truth:
        raise RuntimeError(
            "live rollback blocked; drop truth tables first: " + ",".join(leftover_truth)
        )
    return _drop_tables(engine, _LIVE_DROP_ORDER)


def rollback_rehearsal(target_engine: Engine | None = None) -> dict[str, list[str]]:
    """Drop truth tables, then live parents. Preserves shops, shop_members, and roles."""
    engine = target_engine or default_engine
    with engine.connect() as probe:
        before = set(_public_tables(probe))
        had_identity = "shops" in before and "shop_members" in before
    dropped = _drop_tables(engine, _TRUTH_DROP_ORDER + _LIVE_DROP_ORDER)
    with engine.connect() as probe:
        names = set(_public_tables(probe))
        leftover = [name for name in REHEARSAL_TABLES if name in names]
        if leftover:
            raise RuntimeError(f"rehearsal rollback left tables: {leftover}")
        if had_identity and ("shops" not in names or "shop_members" not in names):
            raise RuntimeError("rehearsal rollback removed identity tables")
    return dropped


def _drop_tables(engine: Engine, names: tuple[str, ...]) -> dict[str, list[str]]:
    migrator = _ident(MIGRATOR_ROLE)
    dropped: list[str] = []
    with engine.begin() as conn:
        if not _role_exists(conn, migrator):
            raise RuntimeError("stashtab_migrator role is missing")
        conn.execute(text(f"SET LOCAL ROLE {migrator}"))
        existing = set(_public_tables(conn))
        for table in names:
            conn.execute(text(f"DROP TABLE IF EXISTS {table}"))
            if table in existing:
                dropped.append(table)
    return {"dropped": dropped}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Live inventory parent migrator")
    parser.add_argument(
        "command",
        choices=(
            "apply",
            "rollback",
            "apply-rehearsal",
            "rollback-rehearsal",
            "apply-f2-receive",
            "rollback-f2-receive-grants",
        ),
    )
    args = parser.parse_args(argv)
    if args.command == "apply":
        print("inventory-live-schema apply:", apply())
    elif args.command == "rollback":
        print("inventory-live-schema rollback:", rollback())
    elif args.command == "apply-rehearsal":
        print("inventory-schema-rehearsal apply:", apply_rehearsal())
    elif args.command == "apply-f2-receive":
        print("inventory-live-schema f2-receive apply:", apply_f2_receive())
    elif args.command == "rollback-f2-receive-grants":
        print("inventory-live-schema f2-receive grant rollback:", rollback_f2_receive_grants())
    else:
        print("inventory-schema-rehearsal rollback:", rollback_rehearsal())
    return 0


if __name__ == "__main__":
    sys.exit(main())
