"""Explicit live-parent migrator for inventory-truth rehearsal.

Creates only inventory_item, purchase_record, and sale. Does not use
metadata.create_all. Types follow the live SQLAlchemy models compiled for
PostgreSQL. Shop-scoped unique (shop_id, id) keys match the frozen truth
composite FK names. Sale.show_session_id stays a nullable string with no FK.

API receives SELECT only. Worker and readonly receive no table access.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

from sqlalchemy import text
from sqlalchemy.engine import Engine

from app.database import engine as default_engine
from app.inventory_truth.migrator import TRUTH_TABLE_NAMES, apply as apply_truth

LIVE_TABLES = ("inventory_item", "purchase_record", "sale")
REHEARSAL_TABLES = LIVE_TABLES + TRUTH_TABLE_NAMES
MIGRATOR_ROLE = "stashtab_migrator"
API_ROLE = "stashtab_api"
WORKER_ROLE = "stashtab_worker"
READONLY_ROLE = "stashtab_readonly"
_RUNTIME_ROLES = (API_ROLE, WORKER_ROLE, READONLY_ROLE)
_TABLE_PRIVS = (
    "SELECT",
    "INSERT",
    "UPDATE",
    "DELETE",
    "TRUNCATE",
    "REFERENCES",
    "TRIGGER",
)
_API_PRIVS = frozenset({"SELECT"})
_ROLE_RE = re.compile(r"^[a-z][a-z0-9_]*$")
_TRUTH_DROP_ORDER = (
    "inventory_adjustment",
    "return_record",
    "refund_record",
    "inventory_exception",
    "inventory_channel_observation",
    "inventory_event",
    "acquisition_lot",
    "inventory_truth_cutover",
)
_LIVE_DROP_ORDER = ("sale", "purchase_record", "inventory_item")

_CREATE_INVENTORY_ITEM = """
CREATE TABLE IF NOT EXISTS inventory_item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id VARCHAR(36) NOT NULL,
    sku VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    set_name VARCHAR(100),
    sequence_number VARCHAR(50),
    cost DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    old_price DOUBLE PRECISION,
    card_type VARCHAR(50),
    variant VARCHAR(50),
    condition VARCHAR(50),
    stock INTEGER NOT NULL,
    last_sync TIMESTAMP WITH TIME ZONE,
    date_added TIMESTAMP WITH TIME ZONE NOT NULL,
    needs_update BOOLEAN NOT NULL,
    needs_review BOOLEAN NOT NULL,
    image_url VARCHAR(512),
    image_locked BOOLEAN NOT NULL,
    sync_status VARCHAR(50) NOT NULL,
    custom_image_url VARCHAR(512),
    shop_listing_price DOUBLE PRECISION,
    sticker_price DOUBLE PRECISION,
    paused_stock INTEGER NOT NULL,
    game VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_inventory_shop_sku UNIQUE (shop_id, sku)
)
"""

_CREATE_PURCHASE_RECORD = """
CREATE TABLE IF NOT EXISTS purchase_record (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id VARCHAR(36) NOT NULL,
    sku VARCHAR(50) NOT NULL,
    quantity INTEGER NOT NULL,
    cost_per_unit DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
)
"""

_CREATE_SALE = """
CREATE TABLE IF NOT EXISTS sale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id VARCHAR(36) NOT NULL,
    item_name VARCHAR(100),
    sku VARCHAR(50),
    sold_price DOUBLE PRECISION,
    profit DOUBLE PRECISION,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    transaction_type VARCHAR(20),
    trade_in_value DOUBLE PRECISION NOT NULL,
    processing_fees DOUBLE PRECISION NOT NULL,
    trade_credit_deduction DOUBLE PRECISION NOT NULL,
    net_revenue DOUBLE PRECISION NOT NULL,
    game VARCHAR(50) NOT NULL,
    show_session_id VARCHAR(36),
    is_reconciled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
)
"""


def _ident(role: str) -> str:
    if not _ROLE_RE.fullmatch(role):
        raise RuntimeError("invalid role name")
    return role


def _role_exists(conn, role: str) -> bool:
    return bool(
        conn.execute(
            text("SELECT 1 FROM pg_roles WHERE rolname = :r"),
            {"r": role},
        ).scalar()
    )


def _role_can_assume(conn, member: str, role: str) -> bool:
    return bool(
        conn.execute(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM pg_auth_members m
                    JOIN pg_roles r ON r.oid = m.roleid
                    JOIN pg_roles u ON u.oid = m.member
                    WHERE r.rolname = :role
                      AND u.rolname = :member
                )
                """
            ),
            {"member": member, "role": role},
        ).scalar()
    )


def _assert_runtime_cannot_assume_migrator(conn) -> None:
    migrator = _ident(MIGRATOR_ROLE)
    blocked = []
    for member in _RUNTIME_ROLES:
        if not _role_exists(conn, member):
            continue
        if _role_can_assume(conn, member, migrator):
            blocked.append(member)
    if blocked:
        raise RuntimeError(
            "prohibited membership: "
            + ",".join(blocked)
            + " can assume stashtab_migrator"
        )


def _has_table_privilege(conn, role: str, table: str, priv: str) -> bool:
    return bool(
        conn.execute(
            text("SELECT has_table_privilege(:role, :rel, :priv)"),
            {"role": role, "rel": f"public.{table}", "priv": priv},
        ).scalar()
    )


def _public_has_table_privilege(conn, table: str, priv: str) -> bool:
    return bool(
        conn.execute(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl, '{}'::aclitem[])) a
                    WHERE n.nspname = 'public'
                      AND c.relname = :table
                      AND a.grantee = 0
                      AND a.privilege_type = :priv
                )
                """
            ),
            {"table": table, "priv": priv},
        ).scalar()
    )


def _public_tables(conn) -> list[str]:
    rows = conn.execute(
        text(
            """
            SELECT c.relname FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND c.relkind = 'r'
            ORDER BY 1
            """
        )
    )
    return [r[0] for r in rows]


def _index_names(conn, table: str) -> set[str]:
    rows = conn.execute(
        text(
            """
            SELECT indexname FROM pg_indexes
            WHERE schemaname = 'public' AND tablename = :table
            """
        ),
        {"table": table},
    )
    return {r[0] for r in rows}


def _constraint_names(conn, table: str) -> set[str]:
    rows = conn.execute(
        text(
            """
            SELECT con.conname
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
            WHERE nsp.nspname = 'public' AND rel.relname = :table
            """
        ),
        {"table": table},
    )
    return {r[0] for r in rows}


def _ensure_index(conn, name: str, table: str, columns: str, unique: bool = False) -> bool:
    if name in _index_names(conn, table):
        return False
    unique_sql = "UNIQUE " if unique else ""
    conn.execute(text(f"CREATE {unique_sql}INDEX IF NOT EXISTS {name} ON {table} ({columns})"))
    return True


def _ensure_shop_fk(conn, table: str) -> bool:
    name = f"fk_{table}_shop_id"
    if name in _constraint_names(conn, table):
        return False
    conn.execute(
        text(
            f"ALTER TABLE {table} ADD CONSTRAINT {name} "
            "FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE RESTRICT"
        )
    )
    return True


def _normalize_privileges(conn, tables: tuple[str, ...]) -> list[str]:
    grants: list[str] = []
    conn.execute(
        text("ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC")
    )
    for role in _RUNTIME_ROLES:
        if _role_exists(conn, role):
            conn.execute(
                text(
                    "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
                    f"REVOKE ALL ON TABLES FROM {_ident(role)}"
                )
            )
    api = _ident(API_ROLE)
    for table in tables:
        conn.execute(text(f"REVOKE ALL PRIVILEGES ON TABLE {table} FROM PUBLIC"))
        for role in _RUNTIME_ROLES:
            if _role_exists(conn, role):
                conn.execute(
                    text(f"REVOKE ALL PRIVILEGES ON TABLE {table} FROM {_ident(role)}")
                )
        if _role_exists(conn, api):
            conn.execute(text(f"GRANT SELECT ON TABLE {table} TO {api}"))
            grants.append(f"{api}:{table}:select")
    return grants


def _assert_select_only(conn, tables: tuple[str, ...]) -> None:
    for table in tables:
        for priv in _TABLE_PRIVS:
            if _public_has_table_privilege(conn, table, priv):
                raise RuntimeError(f"PUBLIC has {priv} on {table}")
        if _role_exists(conn, API_ROLE):
            allowed = {
                priv for priv in _TABLE_PRIVS if _has_table_privilege(conn, API_ROLE, table, priv)
            }
            if allowed != _API_PRIVS:
                raise RuntimeError(
                    f"stashtab_api privileges on {table} are {sorted(allowed)}, "
                    f"expected {sorted(_API_PRIVS)}"
                )
        for role in (WORKER_ROLE, READONLY_ROLE):
            if not _role_exists(conn, role):
                continue
            held = {
                priv for priv in _TABLE_PRIVS if _has_table_privilege(conn, role, table, priv)
            }
            if held:
                raise RuntimeError(f"{role} has table privileges on {table}: {sorted(held)}")


def apply(target_engine: Engine | None = None, *, fail_after: str | None = None) -> dict[str, list[str]]:
    """Create the three live parents in one transaction. Idempotent."""
    engine = target_engine or default_engine
    migrator = _ident(MIGRATOR_ROLE)
    applied: dict[str, list[str]] = {"tables": [], "indexes": [], "foreign_keys": [], "grants": []}
    with engine.begin() as conn:
        if not _role_exists(conn, migrator):
            raise RuntimeError("stashtab_migrator role is missing")
        _assert_runtime_cannot_assume_migrator(conn)
        conn.execute(text(f"SET LOCAL ROLE {migrator}"))
        before = set(_public_tables(conn))
        conn.execute(text(_CREATE_INVENTORY_ITEM))
        conn.execute(text(_CREATE_PURCHASE_RECORD))
        conn.execute(text(_CREATE_SALE))
        for table in LIVE_TABLES:
            if table not in before:
                applied["tables"].append(table)
            conn.execute(text(f"ALTER TABLE {table} OWNER TO {migrator}"))
        if fail_after == "tables":
            raise RuntimeError("injected migration failure after tables")
        for table, sku_index in (
            ("inventory_item", "ix_inventory_item_sku"),
            ("purchase_record", "ix_purchase_record_sku"),
            ("sale", "ix_sale_sku"),
        ):
            if _ensure_index(conn, f"ix_{table}_shop_id", table, "shop_id"):
                applied["indexes"].append(f"ix_{table}_shop_id")
            if _ensure_index(conn, sku_index, table, "sku"):
                applied["indexes"].append(sku_index)
            if _ensure_index(conn, f"uq_{table}_shop_id", table, "shop_id, id", unique=True):
                applied["indexes"].append(f"uq_{table}_shop_id")
        if fail_after == "uniques":
            raise RuntimeError("injected migration failure after uniques")
        for table in LIVE_TABLES:
            if _ensure_shop_fk(conn, table):
                applied["foreign_keys"].append(f"fk_{table}_shop_id")
        if fail_after == "fks":
            raise RuntimeError("injected migration failure after fks")
        applied["grants"] = _normalize_privileges(conn, LIVE_TABLES)
        conn.execute(text("RESET ROLE"))
        _assert_select_only(conn, LIVE_TABLES)
    with engine.connect() as probe:
        names = set(_public_tables(probe))
        missing = [table for table in LIVE_TABLES if table not in names]
        if missing:
            raise RuntimeError(f"live schema verification failed, missing {missing}")
        extra_live = [name for name in ("staging_item", "show_sessions", "pending_trades") if name in names]
        if extra_live:
            raise RuntimeError(f"live schema created forbidden tables: {extra_live}")
        _assert_select_only(probe, LIVE_TABLES)
    return applied


def apply_rehearsal(target_engine: Engine | None = None) -> dict[str, dict[str, list[str]]]:
    """Apply live parents, then the committed truth migrator, then SELECT grants."""
    engine = target_engine or default_engine
    live = apply(engine)
    names = set()
    with engine.connect() as conn:
        names = set(_public_tables(conn))
    missing_parents = [table for table in LIVE_TABLES if table not in names]
    if missing_parents:
        raise RuntimeError(f"truth apply blocked; live parents missing: {missing_parents}")
    previous = os.environ.get("STASHTAB_TRUTH_MIGRATOR_ROLE")
    os.environ["STASHTAB_TRUTH_MIGRATOR_ROLE"] = MIGRATOR_ROLE
    try:
        truth = apply_truth(engine)
    finally:
        if previous is None:
            os.environ.pop("STASHTAB_TRUTH_MIGRATOR_ROLE", None)
        else:
            os.environ["STASHTAB_TRUTH_MIGRATOR_ROLE"] = previous
    with engine.begin() as conn:
        conn.execute(text(f"SET LOCAL ROLE {_ident(MIGRATOR_ROLE)}"))
        grants = _normalize_privileges(conn, REHEARSAL_TABLES)
        conn.execute(text("RESET ROLE"))
        _assert_select_only(conn, REHEARSAL_TABLES)
    return {"live": live, "truth": {k: v for k, v in truth.items() if isinstance(v, list)}, "grants": grants}


def rollback(target_engine: Engine | None = None) -> dict[str, list[str]]:
    """Drop the three live parents. Refuses if truth tables still exist."""
    engine = target_engine or default_engine
    with engine.connect() as probe:
        existing = set(_public_tables(probe))
    leftover_truth = [name for name in TRUTH_TABLE_NAMES if name in existing]
    if leftover_truth:
        raise RuntimeError(
            "live rollback blocked; drop truth tables first: " + ",".join(leftover_truth)
        )
    return _drop_tables(engine, _LIVE_DROP_ORDER)


def rollback_rehearsal(target_engine: Engine | None = None) -> dict[str, list[str]]:
    """Drop truth tables, then live parents. Preserves shops, shop_members, and roles."""
    engine = target_engine or default_engine
    with engine.connect() as probe:
        before = set(_public_tables(probe))
        had_identity = "shops" in before and "shop_members" in before
    dropped = _drop_tables(engine, _TRUTH_DROP_ORDER + _LIVE_DROP_ORDER)
    with engine.connect() as probe:
        names = set(_public_tables(probe))
        leftover = [name for name in REHEARSAL_TABLES if name in names]
        if leftover:
            raise RuntimeError(f"rehearsal rollback left tables: {leftover}")
        if had_identity and ("shops" not in names or "shop_members" not in names):
            raise RuntimeError("rehearsal rollback removed identity tables")
    return dropped


def _drop_tables(engine: Engine, names: tuple[str, ...]) -> dict[str, list[str]]:
    migrator = _ident(MIGRATOR_ROLE)
    dropped: list[str] = []
    with engine.begin() as conn:
        if not _role_exists(conn, migrator):
            raise RuntimeError("stashtab_migrator role is missing")
        conn.execute(text(f"SET LOCAL ROLE {migrator}"))
        existing = set(_public_tables(conn))
        for table in names:
            conn.execute(text(f"DROP TABLE IF EXISTS {table}"))
            if table in existing:
                dropped.append(table)
    return {"dropped": dropped}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Live inventory parent migrator")
    parser.add_argument("command", choices=("apply", "rollback", "apply-rehearsal", "rollback-rehearsal"))
    args = parser.parse_args(argv)
    if args.command == "apply":
        print("inventory-live-schema apply:", apply())
    elif args.command == "rollback":
        print("inventory-live-schema rollback:", rollback())
    elif args.command == "apply-rehearsal":
        print("inventory-schema-rehearsal apply:", apply_rehearsal())
    else:
        print("inventory-schema-rehearsal rollback:", rollback_rehearsal())
    return 0


if __name__ == "__main__":
    sys.exit(main())
